[book]
authors = ["zjp <jiping_zhou@foxmail.com>"]
language = "zh"
multilingual = false
src = "src"
title = "rust-note"

# [preprocessor.theme]
# pagetoc = true
# sidebar-width = "300px"
# pagetoc-width = "15%"
# content-max-width = "75%"
# content-main-margin-left  = "4%"
# content-main-margin-right = "4%"
# nav-chapters-max-width    = "3%"
# nav-chapters-min-width    = "3%"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/zjp-CN/rust-note"
edit-url-template = "https://github.com/zjp-CN/rust-note/edit/main/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false

[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"
